info:
  description: |
    This web page documents the REST API of the FREME project. You can find more information about FREME on the [project website](http://freme-project.eu) and on the
    [FREME GitHub page](http://github.com/freme-project). The [FREME wiki](https://github.com/freme-project/technical-discussion/wiki) contains more technical documentation.

    # General

    This section defines the default parameter set for all FREME e-Services. The parameters have a long and a short form. If both are set, the long form overrides the short form. The API follows the most important points from [NIF API specifications](http://persistence.uni-leipzig.org/nlp2rdf/specification/api.html).

    Please note that all parameters submitted via the URLs query string need to be URL encoded according to [RFC 3986](https://tools.ietf.org/html/rfc3986).

    * input (short form: i):
      * input of the e-Service in plaintext or nif
      * No default
      * Depends on informat and intype
    * informat (short form: f):
      * format of input parameter.
      * possible values
        * text (plaintext)
        * text/turtle (default), short form: turtle
        * application/json+ld, short form: json-ld
        * application/n-triples, short form: n-triples
        * application/rdf+xml, short form: rdf-xml
        * text/n3, short form: n3
    * outformat (short form: o):
      * output format
      * possible values
        * text/turtle (default), short form: turtle
        * application/json+ld, short form: json-ld
        * application/n-triples, short form: n-triples
        * application/rdf+xml, short form: rdf-xml
        * text/n3, short form: n3
    * prefix (short form: p)
      * Controls the url of rdf resources generated from plaintext. Has default value "http://freme-project.eu/"

    The following header values are used by all FREME e-Services
    * Accept
      * possible values
        * turtle for text/turtle (default)
        * json-ld for application/json+ld
        * n-triples for application/n-triples
        * rdf-xml for application/rdf+xml
        * n3 for text/n3
      * When parameter outformat is set then the Accept header is not used by FREME api
    * Content-Type
      * possible values
        * text (plaintext)
        * text/turtle (default), short form: turtle
        * application/json+ld, short form: json-ld
        * application/n-triples, short form: n-triples
        * application/rdf+xml, short form: rdf-xml
        * text/n3, short form: n3
    * When parameter informat is set then the Content-Type header is not used by FREME api

tags:
- name: "e-Translation"

paths:
  /e-publishing/html:
    post:
      description: "Creates an eBook in the EPUB3 format from a zip file containing\
        \ HTML Files and more (images etc.) and a json file containing all necessary\
        \ metadata for the creation of the eBook.\n\n**Example Call**\n\n`curl --form\
        \ \"htmlZip=@alice.zip\" --form metadata='json-string' http://api-dev.freme-project.eu/current/e-publishing/html`\n\
        \n**Metadata JSON may include the following**\n* `titles` - a list of Strings\
        \ where each String represents one title\n* `authors` - a list of Strings\
        \ where each String represents one author\n* `illustrators` - a list of Strings\
        \ where each String represents one illustrator\n* `creators` - a list of Strings\
        \ where each String represents one creator\n* `subjects` - a list of Strings\
        \ where each String represents one subject\n* `coverImage` - the location\
        \ of the cover image inside the zip file\n* `language` - the language of the\
        \ content (e.g., 'en')\n* `source` - the original source of the content\n\
        * `description` - the description of the EPUB\n* `rights` - the rights applicable\
        \ to the EPUB\n* `identifier` - the identifier is represented by 'value',\
        \ 'scheme' is optional and represents the used scheme corresponding with the\
        \ value.\n* `tableOfContents` - it is an ordered list of the chapters/sections\
        \ in the EPUB. For each you provide the title and the corresponding HTML file\
        \ (= resource). If no tableOfContents is provided, the service will do a best\
        \ effort at creating one. However, when no (x)html file is found in the root\
        \ of the zip, the service will return an invalid EPUB.\n\n**Sample .zips**\n\
        * [Alice in wonderland](https://drive.google.com/open?id=0B-qMtkPK-unYbVROT1J2TTRycDg&authuser=0)\n\
        * [A shared culture](https://drive.google.com/open?id=0B-qMtkPK-unYdWlHTWMyS2VaV28&authuser=0)"


  /e-entity/freme-ner/documents:
    post:
      description: "Enriches Text content with entities gathered from various datasets by the FREME-NER Engine. The service accepts plaintext or text sent as NIF document. The text of the nif:isString property (attached to the nif:Context document) will be used for processing. This example shows a NIF document that can be processed by the service:
        \n
        ```
        \n
        @prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> . \n
        @prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> . \n
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n



        <http://example.org/document/1#char=0,21>\n
           a nif:String , nif:Context , nif:RFC5147String ;\n
           nif:isString \"Welcome to Berlin\"^^xsd:string;\n
           nif:beginIndex \"0\"^^xsd:nonNegativeInteger;\n
           nif:endIndex \"21\"^^xsd:nonNegativeInteger;\n
           nif:sourceUrl <http://differentday.blogspot.com/2007_01_01_archive.html> .
        \n
        ```
        \n
        "
    get:
      description: "Enriches Text content with entities gathered from various datasets by the FREME-NER Engine. The service accepts plaintext or text sent as NIF document. The text of the nif:isString property (attached to the nif:Context document) will be used for processing. This example shows a NIF document that can be processed by the service:
        \n
        ```
        \n
        @prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> . \n
        @prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> . \n
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n



        <http://example.org/document/1#char=0,21>\n
           a nif:String , nif:Context , nif:RFC5147String ;\n
           nif:isString \"Welcome to Berlin\"^^xsd:string;\n
           nif:beginIndex \"0\"^^xsd:nonNegativeInteger;\n
           nif:endIndex \"21\"^^xsd:nonNegativeInteger;\n
           nif:sourceUrl <http://differentday.blogspot.com/2007_01_01_archive.html> .
        \n
        ```
        \n
        "

  /e-entity/dbpedia-spotlight/documents:
    post:
      description: "Enriches Text content with entities gathered from various datasets by the DBPedia-Spotlight Engine. The service accepts plaintext or text sent as NIF document. The text of the nif:isString property (attached to the nif:Context document) will be used for processing. This example shows a NIF document that can be processed by the service:
        \n
        ```
        \n
        @prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> . \n
        @prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> . \n
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n



        <http://example.org/document/1#char=0,21>\n
           a nif:String , nif:Context , nif:RFC5147String ;\n
           nif:isString \"Welcome to Berlin\"^^xsd:string;\n
           nif:beginIndex \"0\"^^xsd:nonNegativeInteger;\n
           nif:endIndex \"21\"^^xsd:nonNegativeInteger;\n
           nif:sourceUrl <http://differentday.blogspot.com/2007_01_01_archive.html> .
        \n
        ```
        \n
        "
    get:
      description: "Enriches Text content with entities gathered from various datasets by the DBPedia-Spotlight Engine. The service accepts plaintext or text sent as NIF document. The text of the nif:isString property (attached to the nif:Context document) will be used for processing. This example shows a NIF document that can be processed by the service:
        \n
        ```
        \n
        @prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> . \n
        @prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> . \n
        @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n



        <http://example.org/document/1#char=0,21>\n
           a nif:String , nif:Context , nif:RFC5147String ;\n
           nif:isString \"Welcome to Berlin\"^^xsd:string;\n
           nif:beginIndex \"0\"^^xsd:nonNegativeInteger;\n
           nif:endIndex \"21\"^^xsd:nonNegativeInteger;\n
           nif:sourceUrl <http://differentday.blogspot.com/2007_01_01_archive.html> .
        \n
        ```
        \n
        "



  /e-link/documents/:
    post:
      description: "This service accepts a NIF document (with annotated entities) and performs enrichment with pre-defined templates. The templates contain \"fields\" marked between three at-signs @@@field-name@@@. If a user, while calling the enrichment endpoint specifies an \"unknown\" parameter (not from the list above), then the values of that \"unknown\" parameters will be used to replace with the corresponding \"field\" in the query template. This feature doesn't work via \"Try-it-out!\"-button.\n
        \n
        ```\n

        @prefix dc:    <http://purl.org/dc/elements/1.1/> .\n
        @prefix prov:  <http://www.w3.org/ns/prov#> .\n
        @prefix nif:   <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> .\n
        @prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#> .\n
        @prefix rutp:  <http://rdfunit.aksw.org/data/patterns#> .\n
        @prefix rlog:  <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/rlog#> .\n
        @prefix oslc:  <http://open-services.net/ns/core#> .\n
        @prefix dsp:   <http://dublincore.org/dc-dsp#> .\n
        @prefix dcterms: <http://purl.org/dc/terms/> .\n
        @prefix rutg:  <http://rdfunit.aksw.org/data/generators#> .\n
        @prefix schema: <http://schema.org/> .\n
        @prefix olia:  <http://purl.org/olia/olia.owl#> .\n
        @prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n
        @prefix p:     <http://127.0.0.1:9995/spotlight#> .\n
        @prefix rut:   <http://rdfunit.aksw.org/ns/core#> .\n
        @prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .\n
        @prefix owl:   <http://www.w3.org/2002/07/owl#> .\n
        @prefix rutr:  <http://rdfunit.aksw.org/data/results#> .\n
        @prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n
        @prefix spin:  <http://spinrdf.org/spin#> .\n
        @prefix rutt:  <http://rdfunit.aksw.org/data/tests#> .\n
        @prefix ruts:  <http://rdfunit.aksw.org/data/testsuite#> .\n

        <http://127.0.0.1:9995/spotlight#char=5,7>\n
                a                     nif:Word , nif:RFC5147String ;\n
                nif:anchorOf          \"is\" ;\n
                nif:beginIndex        \"5\" ;\n
                nif:endIndex          \"7\" ;\n
                nif:nextWord          <http://127.0.0.1:9995/spotlight#char=8,15> ;\n
                nif:previousWord      <http://127.0.0.1:9995/spotlight#char=0,4> ;\n
                nif:referenceContext  <http://127.0.0.1:9995/spotlight#char=0,16> ;\n
                nif:sentence          <http://127.0.0.1:9995/spotlight#char=0,16> .\n

        nif:lastWord  a  owl:ObjectProperty .\n
        nif:previousWord  a  owl:ObjectProperty .\n

        <http://127.0.0.1:9995/spotlight#char=0,4>\n
                a                     nif:Word , nif:RFC5147String ;\n
                nif:anchorOf          \"This\" ;\n
                nif:beginIndex        \"0\" ;\n
                nif:endIndex          \"4\" ;\n
                nif:nextWord          <http://127.0.0.1:9995/spotlight#char=5,7> ;\n
                nif:referenceContext  <http://127.0.0.1:9995/spotlight#char=0,16> ;\n
                nif:sentence          <http://127.0.0.1:9995/spotlight#char=0,16> ;\n
                itsrdf:taIdentRef     <http://dbpedia.org/resource/Sathya_Sai_Baba> .\n

        nif:word  a     owl:ObjectProperty .\n
        nif:isString  a  owl:DatatypeProperty .\n
        nif:beginIndex  a  owl:DatatypeProperty .\n
        nif:nextWord  a  owl:ObjectProperty .\n
        nif:sentence  a  owl:ObjectProperty .\n
        nif:anchorOf  a  owl:DatatypeProperty .\n

        <http://127.0.0.1:9995/spotlight#char=0,16>\n
                a                     nif:Context , nif:Sentence , nif:RFC5147String ;\n
                nif:anchorOf          \"This is Germany.\" ;\n
                nif:beginIndex        \"0\" ;\n
                nif:endIndex          \"16\" ;\n
                nif:firstWord         <http://127.0.0.1:9995/spotlight#char=0,4> ;\n
                nif:isString          \"This is Germany.\" ;\n
                nif:lastWord          <http://127.0.0.1:9995/spotlight#char=15,16> ;\n
                nif:referenceContext  <http://127.0.0.1:9995/spotlight#char=0,16> ;\n
                nif:word              <http://127.0.0.1:9995/spotlight#char=5,7> , <http://127.0.0.1:9995/spotlight#char=8,15> .\n

        nif:firstWord  a  owl:ObjectProperty .\n
        nif:Context  a  owl:Class .\n
        rlog:message  a  owl:DatatypeProperty .\n
        nif:Sentence  a  owl:Class .\n
        nif:referenceContext  a  owl:ObjectProperty .\n

        <http://127.0.0.1:9995/spotlight#char=15,16>\n
                a                     nif:Word , nif:RFC5147String ;\n
                nif:anchorOf          \".\" ;\n
                nif:beginIndex        \"15\" ;\n
                nif:endIndex          \"16\" ;\n
                nif:previousWord      <http://127.0.0.1:9995/spotlight#char=8,15> ;\n
                nif:referenceContext  <http://127.0.0.1:9995/spotlight#char=0,16> ;\n
                nif:sentence          <http://127.0.0.1:9995/spotlight#char=0,16> .\n

        nif:endIndex  a  owl:DatatypeProperty .\n

        <http://127.0.0.1:9995/spotlight#char=8,15>\n
                a                     nif:Word , nif:RFC5147String ;\n
                nif:anchorOf          \"Germany\" ;\n
                nif:beginIndex        \"8\" ;\n
                nif:endIndex          \"15\" ;\n
                nif:nextWord          <http://127.0.0.1:9995/spotlight#char=15,16> ;\n
                nif:previousWord      <http://127.0.0.1:9995/spotlight#char=5,7> ;\n
                nif:referenceContext  <http://127.0.0.1:9995/spotlight#char=0,16> ;\n
                nif:sentence          <http://127.0.0.1:9995/spotlight#char=0,16> ;\n
                itsrdf:taIdentRef     <http://dbpedia.org/resource/Germany> .\n

        nif:RFC5147String  a  owl:Class .\n
        nif:Word  a     owl:Class .\n

        ```\n"